backend:
  name: github
  repo: valentingiot/adrenaline-fight-site
  branch: main 

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Accueil"
        name: "index"
        file: "index.html"
        fields:
          - { label: "Titre", name: "title", widget: "string" }
          - { label: "Texte", name: "content", widget: "markdown" }
